### ISSUE TITLE
Advice about rewriting ruby-cbeta to Python

### ISSUE THREAD

**Issue by kylepjohnson** [RayCHOU/ruby-cbeta#1]
Hi,

I'm writing to let you know that I work on an open source project which is looking for someone to rewrite your CBETA reader into Python.

If you have any ideas or would like to help, we would appreciate any help or advice in this ticket: https://github.com/cltk/cltk/issues/140.

Thanks for sharing your work!

**Comment by RayCHOU** [comment]
Hi,

Glad to hear this.
Sorry for my poor English, I cannot speak too much.
I love to help, but first, I am not good in python, so I cannot rewrite ruby-cbeta to python for you.
Second, because of my poor English....

So I talked to @jenjouhung about this information, as he said, CLTK is a famous project in python area, then I know you guys did a great job!
Maybe he will say something later.

I also forwarded your message to a few groups which are interested about programming CBETA, and ask anybody who is interested can contact you:
- https://www.facebook.com/groups/buddhistinformatics/
- https://groups.google.com/forum/#!forum/sutra

**Comment by jenjouhung** [comment]
Talking about the resources for text analysis purpose, we have created some resources that you might get interest:

**I.  Text-analysis friendly CBETA data set** 

The data set is available at https://github.com/DILA-edu/CBETA_TAFxml

To simplify the data pre-processing needs for performing digital analysis on CBETA corpus, we have defined a simplified version of the markup rules, which removed the information irrelevant to the textual analysis, and simplified the text structure to make corpus being easier understood by people who are going to perform digital analysis. We transform most of the original CBETA XMLs to the new markup standard. The Text-analysis friendly CBETA data set has following features:
1. The markups are still compliant with TEI P5.
2. All of the unnecessary information from existing CBETA texts has been taken out, e.g. critical apparatus, markups for menu items, etc.
3. The representation of text structures has been simplified and unified, only the <div> element with “type” attribute is allowed for representing the text structure.
4. Each textual block is wrapped with an <ab> element with a type attribute, which is used to distinguish text block with different types (prose, verse,dharani…). 
5. Every un-displayable character is assigned a unique code point in the Unicode private use area.

**II. CBETA data in plain text format**
The data set is available at https://github.com/DILA-edu/CBETA-txt

The data set is generated by transforming the XML file into plain text format. 
- Each directory represents a text in CBETA. 
- Inside the directory, the filename ends with _000.txt is the content of the whole text. 
- The filename ends with _NNN.txt is the content of NNN-th fascicle of the text. 

Hope you will find useful items from those resources. If you need any further help, please feel free to contact us.

**Comment by kylepjohnson** [comment]
Thank you, both! I really appreciate you sharing your knowledge with me.

@jenjouhung the two corpora you link to are perfect, just what we were hoping for. I will fork these to make them available to CLTK users. I may be in touch, in the near future, for more details about your CBETA corpora.

@RayCHOU and @jenjouhung, the CLTK is now looking for advisors and contributors for Classical Chinese. I would appreciate any introductions or advertising you could do for us. All are free to contact us via our [Issues page](https://github.com/cltk/cltk/issues) or email me directly (mailto:kyle@kyle-p-johnson.com). We are a supportive team and welcome programmers of all skill levels. :bowtie:
